# Generated by Django 5.2.1 on 2025-05-17 08:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, unique=True)),
                ('start_time', models.TimeField(default=datetime.time(0, 0), help_text='Start time for school activities.')),
                ('end_time', models.TimeField(default=datetime.time(0, 0), help_text='End time for school activities.')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('activity_type', models.CharField(choices=[('study', 'Study'), ('break', 'Break'), ('event', 'Event')], default='study', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional description for event activities', max_length=200)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_staff', to='staffs.staff')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='corecode.studentclass')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='corecode.subject')),
                ('daily_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='duty.dailyschedule')),
            ],
            options={
                'ordering': ['daily_schedule__day', 'student_class', 'start_time'],
                'unique_together': {('daily_schedule', 'student_class', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='StaffRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('on_duty', models.BooleanField(default=False)),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_roles', to='corecode.studentclass')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='staffs.staff')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_roles', to='corecode.subject')),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
                'unique_together': {('staff', 'assigned_class', 'subject')},
            },
        ),
    ]
