# Generated by Django 5.2.1 on 2025-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, help_text='Name of the school', max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=15, help_text='Latitude coordinate (-90 to 90 degrees, up to 15 decimal places)', max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=15, help_text='Longitude coordinate (-180 to 180 degrees, up to 15 decimal places)', max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the location was created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the location was last updated')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='SchoolDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week', max_length=10, unique=True)),
                ('start_time', models.TimeField(help_text='Start time of the school day (e.g., 8:00 AM)')),
                ('end_time', models.TimeField(help_text='End time of the school day (e.g., 3:00 PM)')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the school day was created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the school day was last updated')),
            ],
            options={
                'verbose_name': 'School Day',
                'verbose_name_plural': 'School Days',
            },
        ),
        migrations.CreateModel(
            name='SchoolLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
                ('end_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Friday', max_length=10)),
                ('start_time', models.TimeField(default='07:00')),
                ('end_time', models.TimeField(default='19:00')),
                ('is_active', models.BooleanField(default=False)),
                ('distance', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
            ],
        ),
    ]
