# Generated by Django 5.2.1 on 2025-06-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolLocation',
        ),
    ]
