# Generated by Django 5.2.1 on 2025-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_addr', models.CharField(max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('source_addr', models.CharField(default='ELEMENTS', max_length=50)),
                ('length', models.IntegerField(default=0)),
                ('sms_count', models.IntegerField(default=1)),
            ],
        ),
    ]
