# Generated by Django 5.2.1 on 2025-05-17 08:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('firstname', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mobile_number', models.CharField(blank=True, default='255', max_length=12, validators=[django.core.validators.RegexValidator(message='Mobile number must start with 255 followed by 9 digits (e.g., 255123456789).', regex='^255[0-9]{9}$')])),
                ('occupation', models.CharField(blank=True, choices=[('manager_director', 'Manager (Director)'), ('head_master', 'Head Master'), ('second_master', 'Second Master'), ('academic', 'Academic'), ('discipline', 'Discipline'), ('secretary', 'Secretary'), ('librarian', 'Librarian'), ('teacher', 'Teacher'), ('property_admin', 'School Property Administrator'), ('non_teaching', 'Non Teaching Staff')], max_length=50, null=True)),
                ('address', models.TextField(blank=True)),
                ('guarantor', models.CharField(blank=True, max_length=200)),
                ('contract_duration', models.CharField(blank=True, max_length=50)),
                ('nida_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_start_date', models.DateField(default=django.utils.timezone.now)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('passport_photo', models.ImageField(blank=True, upload_to='staffs/passports/')),
                ('others', models.TextField(blank=True)),
                ('staff_user_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_subject_teacher', models.BooleanField(default=False, help_text='Check if this staff teaches subjects.')),
            ],
            options={
                'permissions': [('view_staff_list', 'Can view staff list'), ('view_staff_detail', 'Can view staff details')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='staffs.staff')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='corecode.studentclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='corecode.subject')),
            ],
            options={
                'verbose_name': 'Teacher Subject Assignment',
                'verbose_name_plural': 'Teacher Subject Assignments',
                'ordering': ['staff', 'student_class', 'subject'],
                'unique_together': {('staff', 'student_class', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='teaching_assignments',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='staffs.teachersubjectassignment'),
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=False)),
                ('time_of_arrival', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
