# Generated by Django 5.2.1 on 2025-05-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='occupation',
            field=models.CharField(blank=True, choices=[('head_master', 'Head Master'), ('second_master', 'Second Master'), ('academic', 'Academic'), ('discipline', 'Discipline'), ('secretary', 'Secretary'), ('librarian', 'Librarian'), ('teacher', 'Teacher'), ('property_admin', 'School Property Administrator'), ('non_teaching', 'Non Teaching Staff'), ('bursar', 'Bursar')], max_length=50, null=True),
        ),
    ]
