# Generated by Django 5.2.1 on 2025-05-18 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1, unique=True)),
                ('lower_bound', models.DecimalField(decimal_places=2, help_text='The lowest mark for this grade (inclusive, e.g., 75.50).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('upper_bound', models.DecimalField(decimal_places=2, help_text='The highest mark for this grade (inclusive, e.g., 100.00).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this grade range was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The date and time when this grade range was last updated.')),
            ],
            options={
                'verbose_name': 'Grading System',
                'verbose_name_plural': 'Grading Systems',
            },
        ),
    ]
