# Generated by Django 5.2.1 on 2025-05-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the exam (e.g., Final Exam 2025).', max_length=200)),
                ('is_current', models.BooleanField(default=False, help_text='Indicates if this is the current exam.')),
                ('is_in_progress', models.BooleanField(default=False, help_text='Indicates if this exam is currently in progress.')),
                ('is_users_allowed_to_upload_results', models.BooleanField(default=False, help_text='Indicates if users are allowed to upload results for this exam.')),
                ('is_results_released', models.BooleanField(default=False, help_text='Indicates if the results of this exam have been released.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this exam was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The date and time when this exam was last updated.')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
    ]
