# Generated by Django 5.2.1 on 2025-05-25 09:42

import apps.academics.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_studentinformations'),
        ('corecode', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformations',
            name='academic_comments',
            field=models.TextField(blank=True, help_text="Comments regarding the student's academic performance.", null=True),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='class_teacher_comments',
            field=models.TextField(blank=True, help_text='Comments from the class teacher.', null=True),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='collaboration',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text="The student's collaboration grade.", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='date_of_closing',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='The date when the term closes (defaults to today).', null=True),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='date_of_opening',
            field=models.DateField(blank=True, default=apps.academics.models.get_default_date_of_opening, help_text='The date when the term opens (defaults to one month after closing date).', null=True),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='discipline',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text="The student's discipline grade.", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='The exam associated with this information.', null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.exam'),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='headmaster_comments',
            field=models.TextField(blank=True, help_text='Comments from the headmaster.', null=True),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='religious',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text="The student's religious performance grade.", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The academic session for this information.', null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession'),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='sports_and_games',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text="The student's sports and games grade.", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='student',
            field=models.ForeignKey(blank=True, help_text='The student this information belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='student_class',
            field=models.ForeignKey(blank=True, default=None, help_text='The class of the student for this information.', null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.studentclass'),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='term',
            field=models.ForeignKey(blank=True, help_text='The academic term for this information.', null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm'),
        ),
    ]
