# Generated by Django 5.2.1 on 2025-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_studentinformations_academic_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_combined',
            field=models.BooleanField(default=False, help_text='Indicates if this exam is a combined exam (e.g., combining multiple subjects or sessions).'),
        ),
    ]
