# Generated by Django 5.2.1 on 2025-05-17 08:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('dropped_out', 'Dropped out'), ('shifted', 'Shifted'), ('graduated', 'Graduated')], default='active', max_length=15)),
                ('registration_number', models.CharField(max_length=200, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('father_mobile_number', models.CharField(blank=True, default='255', max_length=12, validators=[django.core.validators.RegexValidator(message="Mobile number must start with '255' followed by 9 digits (e.g., 255123456789).", regex='^255[0-9]{9}$')])),
                ('mother_mobile_number', models.CharField(blank=True, default='255', max_length=12, validators=[django.core.validators.RegexValidator(message="Mobile number must start with '255' followed by 9 digits (e.g., 255123456789).", regex='^255[0-9]{9}$')])),
                ('address', models.TextField(blank=True)),
                ('other_details', models.TextField(blank=True)),
                ('passport', models.ImageField(blank=True, upload_to='students/passports/')),
                ('parent_student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.studentclass')),
            ],
            options={
                'ordering': ['firstname', 'middle_name', 'surname'],
            },
        ),
    ]
