# Generated by Django 5.2.1 on 2025-05-17 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='A 6-digit code used for account verification.', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Confirmation code must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
    ]
