# Generated by Django 5.2.1 on 2025-05-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staffuser_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='admin_name',
            field=models.CharField(default='Ferdinand Barugize', help_text='The full name of the admin.', max_length=200),
        ),
    ]
