# Generated by Django 5.2.1 on 2025-06-05 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminuser_admin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('STUDENT_DETAILS', 'Student Details'), ('FINANCE', 'Finance')], help_text='The type of comment (Academic, Student Details, or Finance).', max_length=20)),
                ('comment_message', models.TextField(blank=True, help_text='The text content of the comment.')),
                ('audio_message', models.FileField(blank=True, help_text='An optional audio file for the comment.', null=True, upload_to='accounts/comments/audio/')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the comment has been read.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when the comment was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The date and time when the comment was last updated.')),
                ('user', models.ForeignKey(help_text='The user who created the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-date_created'],
            },
        ),
    ]
