# Generated by Django 5.2.1 on 2025-06-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_commentsanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsanswer',
            name='comment',
            field=models.OneToOneField(help_text='The comment this answer responds to.', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='accounts.comments'),
        ),
    ]
