# Generated by Django 5.2.1 on 2025-05-27 22:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0002_alter_staff_occupation'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the meeting (e.g., Staff Briefing 2025).', max_length=200)),
                ('status', models.CharField(choices=[('COMING', 'Coming'), ('ONGOING', 'Ongoing'), ('PAST', 'Past')], default='COMING', help_text='The current status of the meeting.', max_length=10)),
                ('meeting_url', models.URLField(blank=True, help_text='URL for the virtual meeting (e.g., Zoom link).', max_length=500)),
                ('from_date', models.DateField(default=django.utils.timezone.now, help_text='The date when the meeting starts.')),
                ('start_time', models.TimeField(help_text='The time when the meeting starts.')),
                ('to_date', models.DateField(default=django.utils.timezone.now, help_text='The date when the meeting ends.')),
                ('to_time', models.TimeField(help_text='The time when the meeting ends.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this meeting was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The date and time when this meeting was last updated.')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['from_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_name', models.CharField(help_text='The name of the agenda item (e.g., Budget Discussion).', max_length=200)),
                ('start_time', models.TimeField(help_text='The start time of this agenda item.')),
                ('end_time', models.TimeField(help_text='The end time of this agenda item.')),
                ('description', models.TextField(blank=True, help_text='Details about this agenda item.')),
                ('meeting', models.ForeignKey(help_text='The meeting this agenda belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(help_text='The meeting this participant is attending.', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('staff', models.ForeignKey(blank=True, help_text='The staff member participating in the meeting.', null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
                ('student', models.ForeignKey(blank=True, help_text='The student participating in the meeting.', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['meeting'],
                'unique_together': {('meeting', 'staff', 'student')},
            },
        ),
    ]
