from django.urls import path
from .views import FinanceHomeView, FeesInvoiceListView

from . import views

urlpatterns = [
    path('finance/', FinanceHomeView.as_view(), name='finance-home'),
    path('finance/fees/create/', views.FeesStructureCreateUpdateView.as_view(), name='fees_structure_create'),
    path('finance/fees/update/<int:pk>/', views.FeesStructureCreateUpdateView.as_view(), name='fees_structure_update'),
    path('finance/fees/', views.FeesStructureListView.as_view(), name='fees_structure_list'),
    path('fees/delete/<int:pk>/', views.FeesStructureDeleteView.as_view(), name='fees_structure_delete'),
    path('invoices/create/', views.FeesInvoiceCreateUpdateView.as_view(), name='fees_invoice_create'),
    path('invoices/update/<int:pk>/', views.FeesInvoiceCreateUpdateView.as_view(), name='fees_invoice_update'),
    path('student-details/<int:pk>/', views.StudentDetailsView.as_view(), name='student_details'),
    path('invoices/', FeesInvoiceListView.as_view(), name='fees_invoice_list'),
    path('invoices/<int:invoice_id>/payment/create/', views.PaymentCreateUpdateView.as_view(), name='payment_create'),
    path('invoices/<int:invoice_id>/payment/<int:pk>/update/', views.PaymentCreateUpdateView.as_view(), name='payment_update'),
    path('invoices/<int:pk>/receipt/', views.FeesInvoiceReceiptView.as_view(), name='fees_invoice_receipt'),
    path('invoices/<int:pk>/', views.FeesInvoiceDetailView.as_view(), name='fees_invoice_detail'),
    path('invoices/<int:pk>/delete/', views.FeesInvoiceDeleteView.as_view(), name='fees_invoice_delete'),
    path('income-categories/create/', views.IncomeCategoryCreateView.as_view(), name='income_category_create'),
    path('income-categories/update/<int:pk>/', views.IncomeCategoryUpdateView.as_view(), name='income_category_update'),
    path('income-categories/', views.IncomeCategoryListView.as_view(), name='income_category_list'),
    path('income-categories/delete/<int:pk>/', views.IncomeCategoryDeleteView.as_view(), name='income_category_delete'),
    path('income-categories/<int:category_id>/school-incomes/create/', views.SchoolIncomeCreateView.as_view(), name='school_income_create'),
    path('school-incomes/update/<int:pk>/', views.SchoolIncomeUpdateView.as_view(), name='school_income_update'),
    path('income-categories/<int:category_id>/school-incomes/', views.SchoolIncomeListView.as_view(), name='school_income_list'),
    path('income-categories/<int:category_id>/school-incomes/<int:pk>/delete/', views.SchoolIncomeDeleteView.as_view(), name='school_income_delete'),
    path('income-categories/<int:category_id>/school-incomes/<int:pk>/', views.SchoolIncomeDetailView.as_view(), name='school_income_detail'),
    path('school-incomes/all/', views.AllSchoolIncomesView.as_view(), name='all_school_incomes'),
    path('expenditure-categories/create/', views.ExpenditureCategoryCreateView.as_view(), name='expenditure_category_create'),
    path('expenditure-categories/<int:pk>/update/', views.ExpenditureCategoryUpdateView.as_view(), name='expenditure_category_update'),
    path('expenditure-categories/<int:pk>/delete/', views.ExpenditureCategoryDeleteView.as_view(), name='expenditure_category_delete'),
    path('expenditure-categories/', views.ExpenditureCategoryListView.as_view(), name='expenditure_category_list'),
    path('expenditure-categories/<int:category_id>/expenditures/create/', views.ExpenditureCreateView.as_view(), name='expenditure_create'),
    path('expenditures/<int:pk>/update/', views.ExpenditureUpdateView.as_view(), name='expenditure_update'),
    path('expenditure-categories/<int:category_id>/expenditures/', views.ExpenditureListView.as_view(), name='expenditure_list'),
    path('expenditure-categories/<int:category_id>/expenditures/<int:expenditure_id>/delete/', views.expenditure_delete, name='expenditure_delete'),
    path('expenditure-categories/<int:category_id>/expenditures/<int:expenditure_id>/', views.expenditure_detail, name='expenditure_detail'),
    path('expenditures/all/', views.ExpenditureAllView.as_view(), name='expenditure_all'),
    path('salaries/create/', views.SalaryCreateView.as_view(), name='salary-create'),
    path('salaries/<int:pk>/update/', views.SalaryUpdateView.as_view(), name='salary-update'),
    path('salaries/', views.SalaryListView.as_view(), name='salary-list'),
    path('salaries/<int:pk>/delete/', views.SalaryDeleteView.as_view(), name='salary-delete'),
    path('salaries/<int:pk>/detail/', views.SalaryDetailView.as_view(), name='salary-detail'),

    path('finance/report/', views.FinancialReportView.as_view(), name='finance-report'),
    path('finance/report/data/', views.FinancialReportDataView.as_view(), name='finance-report-data'),
]