# Generated by Django 5.2.1 on 2025-05-26 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_class_teacher', models.BooleanField(default=False, help_text='Indicates if the staff is a class teacher.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this role was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The date and time when this role was last updated.')),
                ('class_field', models.ForeignKey(blank=True, help_text='The class for which the staff is a class teacher.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.studentclass')),
                ('staff', models.ForeignKey(help_text='The staff member assigned to this role.', on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
            ],
            options={
                'verbose_name': 'Teacher Role',
                'verbose_name_plural': 'Teacher Roles',
                'ordering': ['staff', 'date_created'],
            },
        ),
    ]
