# Generated by Django 5.2.1 on 2025-06-07 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_teachersrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamType',
        ),
    ]
